# Copyright (C) 2026 Maxim [maxirmx] Samsonov (www.sw.consulting)
# All rights reserved.
# This file is a part of Klinok application

services:
  ui-blue:
    image: ghcr.io/maxirmx/klinok.ui:latest
    restart: always
    ports:
      # Direct access only, not routed by Traefik
      - "80:80"
      - "443:443"
    volumes:
      - /home/maxirmx/.certificate:/etc/nginx/certificate:ro

  p2p-blue:
    image: ghcr.io/maxirmx/klinok.p2p-node:latest
    restart: always
    environment:
      KLINOK_P2P_ANNOUNCE: /dns4/klinok.sw.consulting/tcp/8089/tls/ws
      KLINOK_P2P_TLS_CERT: /etc/nginx/certificate/s.crt
      KLINOK_P2P_TLS_KEY: /etc/nginx/certificate/s.key
    ports:
      # Direct access only, not routed by Traefik
      - "8089:8089"
    volumes:
      - /home/maxirmx/.certificate:/etc/nginx/certificate:ro
      - /home/maxirmx/p2p.blue/data:/data:rw
