// Copyright (C) 2026 Maxim [maxirmx] Samsonov (www.sw.consulting)
// All rights reserved.
// This file is a part of Klinok ui application

export type ScenarioRole = "auth" | "owner" | "vet" | "company" | "shared";
export type ScenarioKind = "screen" | "flow" | "state" | "reference";
export type ScenarioComponentName =
  | "AuthScreen"
  | "OwnerHomeScreen"
  | "PetsScreen"
  | "VisitsScreen"
  | "BookingScreen"
  | "DoctorsScreen"
  | "AnalysisScreen"
  | "MaterialsScreen"
  | "ProfileScreen"
  | "RoleLandingScreen";

export interface ScenarioRegistryEntry {
  id: string;
  title: string;
  role: ScenarioRole;
  path: string;
  kind: ScenarioKind;
  figmaNodeId: string;
  exportName?: string;
  component: ScenarioComponentName;
  implemented: boolean;
}

export interface FigmaCoverageEntry {
  id: string;
  source: string;
  status: "implemented" | "duplicate" | "reference-only";
  scenarioId?: string;
  notes: string;
}

export const scenarioRegistry: ScenarioRegistryEntry[] = [
  {
    id: "auth-role",
    title: "Выбор роли",
    role: "auth",
    path: "/auth/role",
    kind: "flow",
    figmaNodeId: "402:28033",
    exportName: "Light / Sign In Screen_Password hide.png",
    component: "AuthScreen",
    implemented: true,
  },
  {
    id: "auth-login",
    title: "Вход по телефону",
    role: "auth",
    path: "/auth/login",
    kind: "flow",
    figmaNodeId: "zip:auth-login",
    exportName: "Light / Sign In Screen_Password hide-*.png",
    component: "AuthScreen",
    implemented: true,
  },
  {
    id: "auth-code",
    title: "Код из СМС",
    role: "auth",
    path: "/auth/code",
    kind: "flow",
    figmaNodeId: "zip:auth-code",
    exportName: "Light / Sign In Screen_Password hide-*.png",
    component: "AuthScreen",
    implemented: true,
  },
  {
    id: "auth-welcome",
    title: "Приветствие",
    role: "auth",
    path: "/auth/welcome",
    kind: "flow",
    figmaNodeId: "zip:auth-welcome",
    exportName: "Light / Sign In Screen_Password hide-*.png",
    component: "AuthScreen",
    implemented: true,
  },
  {
    id: "owner-home",
    title: "Главный экран",
    role: "owner",
    path: "/owner/home",
    kind: "screen",
    figmaNodeId: "402:28167",
    exportName: "Главный экран.png",
    component: "OwnerHomeScreen",
    implemented: true,
  },
  {
    id: "owner-pets",
    title: "Мои питомцы",
    role: "owner",
    path: "/owner/pets",
    kind: "screen",
    figmaNodeId: "zip:owner-pets",
    exportName: "Главный экран-1.png",
    component: "PetsScreen",
    implemented: true,
  },
  {
    id: "owner-pet-detail",
    title: "Карточка питомца",
    role: "owner",
    path: "/owner/pets/:id",
    kind: "screen",
    figmaNodeId: "zip:owner-pet-detail",
    exportName: "Главный экран-1.png",
    component: "PetsScreen",
    implemented: true,
  },
  {
    id: "owner-visits",
    title: "История контактов",
    role: "owner",
    path: "/owner/visits",
    kind: "screen",
    figmaNodeId: "zip:owner-visits",
    exportName: "Посещения / карточка посещения.png",
    component: "VisitsScreen",
    implemented: true,
  },
  {
    id: "owner-visit-detail",
    title: "Карточка посещения",
    role: "owner",
    path: "/owner/visits/:id",
    kind: "screen",
    figmaNodeId: "zip:owner-visit-detail",
    exportName: "Посещения / карточка посещения-1.png",
    component: "VisitsScreen",
    implemented: true,
  },
  {
    id: "owner-booking",
    title: "Запись к врачу",
    role: "owner",
    path: "/owner/booking",
    kind: "flow",
    figmaNodeId: "1:5297",
    exportName: "Wireframe / Запись к врачу",
    component: "BookingScreen",
    implemented: true,
  },
  {
    id: "owner-booking-success",
    title: "Заявка создана",
    role: "owner",
    path: "/owner/booking/success",
    kind: "state",
    figmaNodeId: "zip:booking-success",
    exportName: "Haighlites*.png",
    component: "BookingScreen",
    implemented: true,
  },
  {
    id: "owner-doctors",
    title: "Откликнувшиеся врачи",
    role: "owner",
    path: "/owner/doctors",
    kind: "screen",
    figmaNodeId: "zip:owner-doctors",
    exportName: "Главный экран / Откликнувшиеся врачи",
    component: "DoctorsScreen",
    implemented: true,
  },
  {
    id: "owner-doctor-profile",
    title: "Врач",
    role: "owner",
    path: "/owner/doctors/:id",
    kind: "screen",
    figmaNodeId: "402:38878",
    exportName: "Врач.png",
    component: "DoctorsScreen",
    implemented: true,
  },
  {
    id: "owner-analysis",
    title: "Добавление анализа",
    role: "owner",
    path: "/owner/analysis",
    kind: "flow",
    figmaNodeId: "305:8135",
    exportName: "Добавление анализа.png",
    component: "AnalysisScreen",
    implemented: true,
  },
  {
    id: "owner-analysis-template",
    title: "Шаблоны анализов",
    role: "owner",
    path: "/owner/analysis/templates",
    kind: "screen",
    figmaNodeId: "zip:analysis-template",
    exportName: "Шаблон*.png",
    component: "AnalysisScreen",
    implemented: true,
  },
  {
    id: "owner-analysis-saved",
    title: "Анализ сохранен",
    role: "owner",
    path: "/owner/analysis/saved",
    kind: "state",
    figmaNodeId: "zip:analysis-saved",
    exportName: "Добавление анализа-*.png",
    component: "AnalysisScreen",
    implemented: true,
  },
  {
    id: "owner-materials",
    title: "Справочник",
    role: "owner",
    path: "/owner/materials",
    kind: "screen",
    figmaNodeId: "zip:materials",
    exportName: "Справочник.png",
    component: "MaterialsScreen",
    implemented: true,
  },
  {
    id: "owner-drug-create",
    title: "Новый препарат",
    role: "owner",
    path: "/owner/materials/drugs/new",
    kind: "flow",
    figmaNodeId: "issue:14",
    exportName: "GitHub issue #14",
    component: "MaterialsScreen",
    implemented: true,
  },
  {
    id: "owner-drug-detail",
    title: "Препарат",
    role: "owner",
    path: "/owner/materials/drugs/:id",
    kind: "screen",
    figmaNodeId: "issue:14",
    exportName: "GitHub issue #14",
    component: "MaterialsScreen",
    implemented: true,
  },
  {
    id: "owner-drug-edit",
    title: "Редактировать препарат",
    role: "owner",
    path: "/owner/materials/drugs/:id/edit",
    kind: "flow",
    figmaNodeId: "issue:14",
    exportName: "GitHub issue #14",
    component: "MaterialsScreen",
    implemented: true,
  },
  {
    id: "owner-material-detail",
    title: "Материал справочника",
    role: "owner",
    path: "/owner/materials/:id",
    kind: "screen",
    figmaNodeId: "zip:material-detail",
    exportName: "Справочник.png",
    component: "MaterialsScreen",
    implemented: true,
  },
  {
    id: "owner-profile",
    title: "Мой профиль",
    role: "owner",
    path: "/owner/profile",
    kind: "screen",
    figmaNodeId: "zip:owner-profile",
    exportName: "Мой профиль.png",
    component: "ProfileScreen",
    implemented: true,
  },
  {
    id: "owner-profile-notifications",
    title: "Уведомления",
    role: "owner",
    path: "/owner/profile/notifications",
    kind: "screen",
    figmaNodeId: "zip:profile-notifications",
    exportName: "Мой профиль / уведомления*.png",
    component: "ProfileScreen",
    implemented: true,
  },
  {
    id: "owner-profile-about",
    title: "О приложении",
    role: "owner",
    path: "/owner/profile/about",
    kind: "screen",
    figmaNodeId: "zip:profile-about",
    exportName: "Мой профиль / о приложении*.png",
    component: "ProfileScreen",
    implemented: true,
  },
  {
    id: "owner-profile-faq",
    title: "FAQ",
    role: "owner",
    path: "/owner/profile/faq",
    kind: "screen",
    figmaNodeId: "zip:profile-faq",
    exportName: "Мой профиль / FAQ*.png",
    component: "ProfileScreen",
    implemented: true,
  },
  {
    id: "owner-profile-delete",
    title: "Удалить аккаунт",
    role: "owner",
    path: "/owner/profile/delete",
    kind: "flow",
    figmaNodeId: "zip:profile-delete",
    exportName: "Мой профиль / удалить аккаунт*.png",
    component: "ProfileScreen",
    implemented: true,
  },
  {
    id: "vet-home",
    title: "Кабинет ветеринара",
    role: "vet",
    path: "/vet/home",
    kind: "screen",
    figmaNodeId: "zip:vet-home",
    exportName: "Light / Sign In Screen_Password hide-*.png",
    component: "RoleLandingScreen",
    implemented: true,
  },
  {
    id: "vet-requests",
    title: "Заявки ветеринара",
    role: "vet",
    path: "/vet/requests",
    kind: "screen",
    figmaNodeId: "zip:vet-requests",
    exportName: "Light / Sign In Screen_Password hide-*.png",
    component: "RoleLandingScreen",
    implemented: true,
  },
  {
    id: "vet-profile",
    title: "Профиль ветеринара",
    role: "vet",
    path: "/vet/profile",
    kind: "screen",
    figmaNodeId: "zip:vet-profile",
    exportName: "Light / Sign In Screen_Password hide-*.png",
    component: "RoleLandingScreen",
    implemented: true,
  },
  {
    id: "company-home",
    title: "Кабинет юрлица",
    role: "company",
    path: "/company/home",
    kind: "screen",
    figmaNodeId: "zip:company-home",
    exportName: "Light / Sign In Screen_Password hide-*.png",
    component: "RoleLandingScreen",
    implemented: true,
  },
  {
    id: "company-profile",
    title: "Профиль юрлица",
    role: "company",
    path: "/company/profile",
    kind: "screen",
    figmaNodeId: "zip:company-profile",
    exportName: "Light / Sign In Screen_Password hide-*.png",
    component: "RoleLandingScreen",
    implemented: true,
  },
];

export const figmaCoverage: FigmaCoverageEntry[] = [
  {
    id: "live-auth-role",
    source: "Figma node 402:28033",
    status: "implemented",
    scenarioId: "auth-role",
    notes: "Live MCP context used for role selection layout and copy; iOS chrome removed.",
  },
  {
    id: "live-owner-home",
    source: "Figma node 402:28167",
    status: "implemented",
    scenarioId: "owner-home",
    notes: "Live MCP context used for owner dashboard structure, labels, and spacing.",
  },
  {
    id: "live-booking",
    source: "Figma node 1:5297",
    status: "implemented",
    scenarioId: "owner-booking",
    notes: "Live MCP context used for booking fields and action hierarchy.",
  },
  {
    id: "live-doctor-profile",
    source: "Figma node 402:38878",
    status: "implemented",
    scenarioId: "owner-doctor-profile",
    notes: "Live MCP context used for doctor details and services.",
  },
  {
    id: "zip-auth-variants",
    source: "Light / Sign In Screen_Password hide.png through -31.png",
    status: "implemented",
    scenarioId: "auth-login",
    notes: "Covered as the role, login, SMS code, and welcome flow instead of near-duplicate frames.",
  },
  {
    id: "zip-visit-frames",
    source: "Посещения / карточка посещения*.png",
    status: "implemented",
    scenarioId: "owner-visit-detail",
    notes: "Covered as visit list plus document detail states.",
  },
  {
    id: "zip-analysis-variants",
    source: "Добавление анализа.png through Добавление анализа-36.png",
    status: "implemented",
    scenarioId: "owner-analysis",
    notes: "Covered as add analysis, template selection, and saved confirmation states.",
  },
  {
    id: "zip-template-variants",
    source: "Шаблон*.png",
    status: "implemented",
    scenarioId: "owner-analysis-template",
    notes: "Covered by the template list and template preview flow.",
  },
  {
    id: "zip-profile-subpages",
    source: "Мой профиль*.png",
    status: "implemented",
    scenarioId: "owner-profile",
    notes: "Covered by profile, notifications, about, FAQ, and delete-account routes.",
  },
  {
    id: "zip-highlights",
    source: "Haighlites*.png",
    status: "duplicate",
    scenarioId: "owner-booking-success",
    notes: "Visual highlight/export variants are represented by existing success and dashboard states.",
  },
  {
    id: "source-ios-chrome",
    source: "Status bar, Dynamic Island, home indicator, keyboard screenshots",
    status: "reference-only",
    notes: "These are source export artifacts and are deliberately omitted from the prototype DOM and CSS.",
  },
];

export function getScenarioById(id: string) {
  return scenarioRegistry.find((scenario) => scenario.id === id);
}
